include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
    - "**/*.gen.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    prefer_relative_imports: true
    avoid_classes_with_only_static_members: false
    always_use_package_imports: false
    sort_pub_dependencies: false
    use_super_parameters: false
    use_decorated_box: false
    # sort_constructors_first: true
    # prefer_double_quotes: true
    # prefer_single_quotes: true
