targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
      json_serializable:
        enabled: true
        generate_for:
          include:
            - lib/**.dart