// Mocks generated by Mockito 5.2.0 from annotations
// in riverpod_boilerplate/test/mocks/repositories/repositories_mock.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_boilerplate/domain/enums/account_type.dart' as _i5;
import 'package:riverpod_boilerplate/domain/repositories/auth_repository.dart'
    as _i3;
import 'package:riverpod_boilerplate/domain/states/login/login_state.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeLoginState_0 extends _i1.Fake implements _i2.LoginState {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.LoginState> login(_i5.AccountType? accountType) =>
      (super.noSuchMethod(Invocation.method(#login, [accountType]),
              returnValue: Future<_i2.LoginState>.value(_FakeLoginState_0()))
          as _i4.Future<_i2.LoginState>);
  @override
  _i4.Future<void> logout(_i5.AccountType? accountType) =>
      (super.noSuchMethod(Invocation.method(#logout, [accountType]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<_i2.LoginState> guestLogin(String? name) =>
      (super.noSuchMethod(Invocation.method(#guestLogin, [name]),
              returnValue: Future<_i2.LoginState>.value(_FakeLoginState_0()))
          as _i4.Future<_i2.LoginState>);
}
