// Mocks generated by Mockito 5.4.2 from annotations
// in riverpod_boilerplate/test/mocks/repositories/repositories_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:riverpod_boilerplate/data/models/result/data_state.dart' as _i4;
import 'package:riverpod_boilerplate/domain/enums/account_type.dart' as _i6;
import 'package:riverpod_boilerplate/domain/models/user/user.dart' as _i5;
import 'package:riverpod_boilerplate/domain/repositories/auth_repository.dart'
    as _i2;
import 'package:riverpod_boilerplate/domain/repositories/user_repository.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i2.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataState<_i5.User>> login(_i6.AccountType? accountType) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [accountType],
        ),
        returnValue: _i3.Future<_i4.DataState<_i5.User>>.value(
            _i7.dummyValue<_i4.DataState<_i5.User>>(
          this,
          Invocation.method(
            #login,
            [accountType],
          ),
        )),
      ) as _i3.Future<_i4.DataState<_i5.User>>);
  @override
  _i3.Future<void> logout(_i6.AccountType? accountType) => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [accountType],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i8.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.DataState<_i5.User>> readUser() => (super.noSuchMethod(
        Invocation.method(
          #readUser,
          [],
        ),
        returnValue: _i3.Future<_i4.DataState<_i5.User>>.value(
            _i7.dummyValue<_i4.DataState<_i5.User>>(
          this,
          Invocation.method(
            #readUser,
            [],
          ),
        )),
      ) as _i3.Future<_i4.DataState<_i5.User>>);
  @override
  _i3.Future<_i4.DataState<_i5.User>> createUser(
    String? token,
    _i6.AccountType? accountType,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createUser,
          [
            token,
            accountType,
          ],
        ),
        returnValue: _i3.Future<_i4.DataState<_i5.User>>.value(
            _i7.dummyValue<_i4.DataState<_i5.User>>(
          this,
          Invocation.method(
            #createUser,
            [
              token,
              accountType,
            ],
          ),
        )),
      ) as _i3.Future<_i4.DataState<_i5.User>>);
  @override
  _i3.Future<bool> updateUser(_i5.User? user) => (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [user],
        ),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
  @override
  _i3.Future<void> removeUser() => (super.noSuchMethod(
        Invocation.method(
          #removeUser,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
