// Mocks generated by Mockito 5.3.2 from annotations
// in riverpod_boilerplate/test/mocks/usecases/usecases_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riverpod_boilerplate/data/models/result/data_state.dart' as _i2;
import 'package:riverpod_boilerplate/domain/enums/account_type.dart' as _i7;
import 'package:riverpod_boilerplate/domain/models/user/user.dart' as _i6;
import 'package:riverpod_boilerplate/domain/states/core/theme/theme_state.dart'
    as _i3;
import 'package:riverpod_boilerplate/domain/usecases/auth/auth_usecases.dart'
    as _i4;
import 'package:riverpod_boilerplate/domain/usecases/storage/onboarding/onboarding_usecases.dart'
    as _i10;
import 'package:riverpod_boilerplate/domain/usecases/storage/theme/theme_storage_usecases.dart'
    as _i9;
import 'package:riverpod_boilerplate/domain/usecases/user/user_usecases.dart'
    as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDataState_0<T> extends _i1.SmartFake implements _i2.DataState<T> {
  _FakeDataState_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeState_1 extends _i1.SmartFake implements _i3.ThemeState {
  _FakeThemeState_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LoginUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginUser extends _i1.Mock implements _i4.LoginUser {
  MockLoginUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DataState<_i6.User>> call(_i7.AccountType? accountType) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [accountType],
        ),
        returnValue: _i5.Future<_i2.DataState<_i6.User>>.value(
            _FakeDataState_0<_i6.User>(
          this,
          Invocation.method(
            #call,
            [accountType],
          ),
        )),
      ) as _i5.Future<_i2.DataState<_i6.User>>);
}

/// A class which mocks [LogoutUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogoutUser extends _i1.Mock implements _i4.LogoutUser {
  MockLogoutUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(_i7.AccountType? accountType) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [accountType],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ReadUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadUser extends _i1.Mock implements _i8.ReadUser {
  MockReadUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.DataState<_i6.User>> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i2.DataState<_i6.User>>.value(
            _FakeDataState_0<_i6.User>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i2.DataState<_i6.User>>);
}

/// A class which mocks [UpdateUser].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUser extends _i1.Mock implements _i8.UpdateUser {
  MockUpdateUser() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call(_i6.User? user) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [user],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [ReadTheme].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadTheme extends _i1.Mock implements _i9.ReadTheme {
  MockReadTheme() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ThemeState> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<_i3.ThemeState>.value(_FakeThemeState_1(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i5.Future<_i3.ThemeState>);
}

/// A class which mocks [WriteTheme].
///
/// See the documentation for Mockito's code generation for more information.
class MockWriteTheme extends _i1.Mock implements _i9.WriteTheme {
  MockWriteTheme() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(_i3.ThemeState? themeState) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [themeState],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [ReadOnboarding].
///
/// See the documentation for Mockito's code generation for more information.
class MockReadOnboarding extends _i1.Mock implements _i10.ReadOnboarding {
  MockReadOnboarding() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> call() => (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
}

/// A class which mocks [WriteOnboarding].
///
/// See the documentation for Mockito's code generation for more information.
class MockWriteOnboarding extends _i1.Mock implements _i10.WriteOnboarding {
  MockWriteOnboarding() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<void> call(bool? isOnboardingComplete) => (super.noSuchMethod(
        Invocation.method(
          #call,
          [isOnboardingComplete],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
